on:
  workflow_call:
    inputs:
      docker_repo_name:
        required: false
        type: string
        default: "gcr.io"

      docker_registry_name:
        required: false
        type: string
        default: "p3marketers-manage"

      image_name:
        required: true
        type: string

      tags:
        description: "Multiline string with newline element separation"
        required: true
        type: string

      GKE_CLUSTER:
        type: string
        required: true

      GKE_ZONE:
        type: string
        required: false
        default: "europe-west1-d"

      PROJECT_ID:
        type: string
        required: true

      BUILD_ARGS:
        type: string
        required: false
        default: ""

      DEPLOYMENT_NAME:
        type: string
        required: true

jobs:
  checkout_build__and_build_app:
    name: checkout, build and build app
    runs-on: self-hosted
    environment: production

    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: google auth
        id: auth
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      - uses: 'docker/login-action@v1'
        with:
          registry: ${{inputs.docker_repo_name}}
          username: _json_key
          password: "${{ secrets.GCP_CREDENTIALS }}"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Set up GKE credentials
        uses: google-github-actions/get-gke-credentials@v0
        with:
          cluster_name: ${{ inputs.GKE_CLUSTER }}
          location: ${{ inputs.GKE_ZONE }}
          project_id: ${{ inputs.PROJECT_ID }}

      - name: docker image metadata
        id: image-meta
        uses: docker/metadata-action@v4
        with:
          tags: ${{ inputs.tags }}
          images: |
            ${{inputs.docker_repo_name}}/${{inputs.docker_registry_name}}/${{inputs.image_name}}

      # Build and Push the Docker image
      - name: Build and Push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ${{ steps.image-meta.outputs.tags }}
          build-args: ${{ inputs.BUILD_ARGS }}

      # Deploy the Docker image to the GKE cluster
      - name: Deploy
        run: |-
          kubectl rollout restart deployment/${{inputs.DEPLOYMENT_NAME}}